# -*- coding: utf-8 -*-
"""AgentModelSettings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfOusb_ukX8bXIgpAJo8O6SiqSN7k2yJ
"""

"""
SASD Survey Analysis Pipeline v7 — ABM Migration Slovakia
Google Colab

ИЗМЕНЕНИЯ v7 относительно v6:
  1. ИСПРАВЛЕНИЕ ЗНАКОВ EFA: после run_efa добавляется автоматическая проверка
     знака — если большинство нагрузок отрицательные, фактор инвертируется.
     Это устраняет системную проблему, при которой social_embeddedness=0.23
     при высоких сырых значениях O36.
  2. СОСТАВНЫЕ ПАРАМЕТРЫ (Ячейка 5b):
     - info_quality_final: info_seeking (2017) + info_quality_digital (2024),
       веса из объяснённой дисперсии EFA (40.5% и 67.1% → 0.38 и 0.62)
     - inertia_social_component: social_embeddedness + strong_ties_quality (2017)
       + family_domain_weight (2022), веса из дисперсии (55.1%, 64.1%, 37.0%)
  3. УДАЛЁН job_satisfaction как самостоятельный параметр — Q23 уже входит
     в econ_perceived_control с нагрузкой -0.801. Дублирование устранено.
  4. econ_perceived_control оставлен отдельным (не сводится с perceived_control):
     содержательно это job satisfaction + org identity, а не локус контроля.
  5. perceived_control: исправлены знаки инверсии O28A/O28B (теперь True,
     были False в v6 — они измеряют несчастье/беспомощность, высокий = плохо).

Структура файлов (*full.xlsx):
  Rawdata:       строка 0 = имена, строка 1 = метки, строки 2+ = данные
  ListVariables: строка 0 = имена, строка 3 = тип шкалы, строки 5+ = коды "N | label"

Sentinel-коды задаются ЛОКАЛЬНО для каждой переменной в момент подачи в батарею.
При загрузке глобально удаляются только коды с однозначным смыслом "отказ/не знаю":
  все датасеты: {99, -9}
  2022 и 2024:  дополнительно {-8}
  2024:         дополнительно {99999}
"""

# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 0 — Установка
# ══════════════════════════════════════════════════════════════════════════════
# !pip install factor_analyzer prince -q

import re, json, warnings
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
warnings.filterwarnings('ignore')
print("✓ Библиотеки загружены")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 1 — Пути и загрузка данных
# ══════════════════════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

DRIVE    = "/content/drive/MyDrive/"
OUT_JSON = DRIVE + "agent_params_from_survey.json"
OUT_CSV  = DRIVE + "agent_params_summary.csv"

FILES = {
    "2016": DRIVE + "Pracovne2016full.xlsx",
    "2017": DRIVE + "Soc_siete2017full.xlsx",
    "2022": DRIVE + "Soc_roly2022full.xlsx",
    "2020": DRIVE + "Brain_drain2020full.xlsx",
    "2024": DRIVE + "DigitalCommunication2024.xlsx",
}

SENTINEL_BASE = {99, -9}
SENTINEL_2022 = SENTINEL_BASE | {-8}
SENTINEL_2024 = SENTINEL_BASE | {-8, 99999}


def load_dataset(year: str):
    """
    Возвращает (df, codebook) или (None, None).
    codebook = {VAR_UPPER: {'scale': str, 'codes': {int: str}}}
    """
    import os
    path = FILES[year]
    if not os.path.exists(path):
        print(f"  [{year}] ✗ не найден: {path}")
        return None, None

    from openpyxl import load_workbook
    wb = load_workbook(path, read_only=True)

    ws = wb['Rawdata']
    all_rows  = list(ws.iter_rows(values_only=True))
    col_names = [str(v).strip() if v else f'_c{i}' for i, v in enumerate(all_rows[0])]
    data      = [list(r) for r in all_rows[2:]]
    df        = pd.DataFrame(data, columns=col_names[:len(data[0])])

    sentinel = SENTINEL_2022 if year == "2022" else SENTINEL_2024 if year == "2024" else SENTINEL_BASE
    for c in df.columns:
        s = pd.to_numeric(df[c], errors='coerce')
        df[c] = s.where(~s.isin(sentinel), np.nan)

    ws_lv    = wb['ListVariables']
    lv       = list(ws_lv.iter_rows(values_only=True))
    lv_names = [str(v).strip().upper() if v else '' for v in lv[0]]
    scale_row = lv[3] if len(lv) > 3 else []
    codebook  = {}
    for ci, varname in enumerate(lv_names):
        if not varname:
            continue
        scale = str(scale_row[ci]).strip() if ci < len(scale_row) and scale_row[ci] else 'unknown'
        codes = {}
        for ri in range(5, len(lv)):
            cell = lv[ri][ci] if ci < len(lv[ri]) else None
            if cell is None:
                continue
            m = re.match(r'^(-?\d+)\s*\|\s*(.+)$', str(cell).strip())
            if m:
                codes[int(m.group(1))] = m.group(2).strip()
        codebook[varname] = {'scale': scale, 'codes': codes}

    print(f"  [{year}] {df.shape[0]} строк × {df.shape[1]} столбцов  |  кодбук: {len(codebook)} перем.")
    return df, codebook


print("Загрузка датасетов...")
df16, cb16 = load_dataset("2016")
df17, cb17 = load_dataset("2017")
df22, cb22 = load_dataset("2022")
df20, cb20 = load_dataset("2020")
df24, cb24 = load_dataset("2024")
print("✓ Загрузка завершена")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 2 — Вспомогательные функции
# ══════════════════════════════════════════════════════════════════════════════

def get_col(df, name, invert=False, mask=None):
    """
    Возвращает числовую серию столбца.
    invert=True: инвертирует шкалу через (max + min - x).
    mask: список значений → заменяются на NaN перед остальными операциями.
    """
    key = next((c for c in df.columns if c.upper() == name.upper()), None)
    if key is None:
        return pd.Series(np.nan, index=df.index, name=name)
    s = pd.to_numeric(df[key], errors='coerce').rename(name)
    if mask:
        s = s.where(~s.isin(mask), np.nan)
    if invert:
        vmax, vmin = s.max(), s.min()
        s = (vmax + vmin - s).rename(name)
    return s


def build_battery(df, spec):
    """
    Собирает батарею переменных и выводит диагностику.
    spec = {col_name: (invert_bool, mask_list_or_None)}
    Короткий синтаксис: {col_name: invert_bool} — mask = None.
    """
    result = {}
    for varname, opts in spec.items():
        if isinstance(opts, bool):
            inv, mask = opts, None
        else:
            inv, mask = opts
        s = get_col(df, varname, invert=inv, mask=mask)
        if s.notna().sum() > 0:
            result[varname] = s
            print(f"    {varname}: mean={s.mean():.2f}  NaN={s.isna().mean():.0%}"
                  + ("  [инверт]" if inv else "")
                  + (f"  [маска {mask}]" if mask else ""))
        else:
            print(f"    {varname}: ✗ нет данных")
    return pd.DataFrame(result, index=df.index)


def norm01(s):
    """
    Ранговая нормализация (процентильный ранг) → [0, 1].

    В отличие от MinMaxScaler, сохраняет форму распределения:
      - скошенность не растягивается
      - выбросы не задают крайние точки
      - доля агентов ниже порога приближена к реальной популяции

    Использует scipy.stats.rankdata — при недоступности scipy
    fallback на MinMaxScaler.
    """
    idx  = s.dropna().index
    vals = s.dropna().values
    if len(vals) < 2:
        return s
    try:
        from scipy.stats import rankdata
        ranks = rankdata(vals) / (len(vals) + 1)
    except ImportError:
        # Fallback: MinMax (старый метод)
        out = s.copy().astype(float)
        out[idx] = MinMaxScaler().fit_transform(vals.reshape(-1, 1)).flatten()
        return out
    out = s.copy().astype(float)
    out[idx] = ranks
    return out


print("✓ Вспомогательные функции готовы")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 3 — Демография
# ══════════════════════════════════════════════════════════════════════════════

EDU    = {1:"low",2:"low",3:"low",4:"low",5:"low",
          6:"medium",7:"medium",8:"medium",9:"medium",
          10:"high",11:"high",12:"high"}
REGION = {1:"BA",2:"TT",3:"TN",4:"NR",5:"ZA",6:"BB",7:"PO",8:"KE"}
MARITAL = {1:"single",2:"married",3:"partner",4:"divorced",5:"widowed"}

SETT_16 = {1:"rural",2:"small_city",3:"small_city",4:"city",5:"metro"}
SETT_17 = {1:"city",2:"city",3:"small_city",4:"rural",5:"rural"}
SETT_22 = {1:"rural",2:"small_city",3:"small_city",4:"small_city",5:"city",6:"city",7:"metro"}


def demographics(df, year_ref, year_col, edu_col, sex_col,
                 region_col=None, sett_col=None, sett_map=None, marital_col=None, label=""):
    birth = get_col(df, year_col)
    age   = (year_ref - birth) if birth.median() > 1900 else birth
    d = {
        'age':       age,
        'age_group': pd.cut(age, bins=[17,30,45,60,100], labels=["18-30","31-45","46-60","60+"]),
        'edu_group': get_col(df, edu_col).map(EDU),
        'sex':       get_col(df, sex_col).map({1:"male",2:"female"}),
    }
    if region_col:
        d['region']     = get_col(df, region_col).map(REGION)
    if sett_col and sett_map:
        d['settlement'] = get_col(df, sett_col).map(sett_map)
    if marital_col:
        d['marital']    = get_col(df, marital_col).map(MARITAL)
    demo = pd.DataFrame(d, index=df.index)
    print(f"  [{label}] возраст mean={demo['age'].mean():.1f} | "
          f"образование: {demo['edu_group'].value_counts(dropna=True).to_dict()}")
    return demo


print("Строим демографию...")
demo16 = demographics(df16, 2016, 'B2',        'B4',       'B1',
                      region_col='Kodkraja', sett_col='vmb', sett_map=SETT_16,
                      marital_col='B34', label="2016") if df16 is not None else None
demo17 = demographics(df17, 2017, 'B02',       'B04',      'B01',
                      region_col='REG',      sett_col='B45', sett_map=SETT_17,
                      marital_col='B42', label="2017") if df17 is not None else None
demo22 = demographics(df22, 2022, 'B2',        'b4',       'b1',
                      region_col='kraj',     sett_col='vmb', sett_map=SETT_22,
                      marital_col='b34', label="2022") if df22 is not None else None
demo24 = demographics(df24, 2024, 'BIRTH_AGE', 'NAT_DEGR', 'SEX',
                      region_col='KRAJ', label="2024") if df24 is not None else None
print("✓ Демография готова")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 4 — EFA и MCA
# ══════════════════════════════════════════════════════════════════════════════
from factor_analyzer import FactorAnalyzer, calculate_bartlett_sphericity, calculate_kmo


# ── Экспертные веса для составных параметров (v8) ──────────────────────────
# Замена EFA-дисперсии: объяснённая дисперсия EFA меряет «похожесть вопросов»
# внутри батареи, а не содержательную важность конструкта.
# Веса ниже — экспертная оценка относительной важности компонент.
COMPOSITE_WEIGHTS = {
    'info_quality_final': {
        # Умение оценивать информацию (цифровые навыки) важнее,
        # чем интенсивность её поиска — примерно 65/35.
        'info_seeking':         0.35,
        'info_quality_digital': 0.65,
    },
    'inertia_social_component': {
        # Качество сильных связей — главный якорь инерции.
        # Включённость в сеть и семейные обязательства — примерно поровну.
        'social_embeddedness':  0.30,
        'strong_ties_quality':  0.40,
        'family_domain_weight': 0.30,
    },
}

# Старые EFA_VARIANCE оставлены для справки, но не используются в v8.
EFA_VARIANCE = {
    'perceived_control':    28.0,
    'social_embeddedness':  55.1,
    'social_domain_weight': 38.5,
    'strong_ties_quality':  64.1,
    'future_orientation':   35.8,
    'info_seeking':         40.5,
    'family_domain_weight': 37.0,
    'economic_sensitivity': 34.4,
    'econ_perceived_control': 40.3,
    'org_loyalty':          46.7,
    'place_aspiration':     36.3,
    'work_family_conflict': 27.3,
    'info_quality_digital': 67.1,
}


def run_efa(bat, name):
    """
    EFA (minres, 1 фактор) если Bartlett p<0.05 и KMO>0.5.
    Иначе — простое среднее. Выводит нагрузки и % объяснённой дисперсии.

    ИСПРАВЛЕНИЕ v7: после извлечения фактора проверяем знак нагрузок.
    Если большинство нагрузок отрицательные — инвертируем фактор.
    Это устраняет ситуацию когда высокий сырой балл (хорошие O36)
    давал низкий факторный балл после нормализации.
    """
    clean = bat.dropna()
    n, k  = clean.shape
    print(f"  [{name}] n={n}  k={k}")
    if n < 50 or k < 2:
        print(f"  [{name}] → мало данных, среднее")
        return bat.mean(axis=1).rename(name)
    try:
        _, p   = calculate_bartlett_sphericity(clean)
        _, kmo = calculate_kmo(clean)
    except Exception as e:
        print(f"  [{name}] ошибка теста: {e} → среднее")
        return bat.mean(axis=1).rename(name)
    ok = p < 0.05 and kmo > 0.5
    print(f"  [{name}] Bartlett p={p:.4f}{'✓' if p<0.05 else '✗'}  KMO={kmo:.3f}{'✓' if kmo>0.5 else '✗'}")
    if not ok:
        print(f"  [{name}] → EFA не рекомендован, среднее")
        return bat.mean(axis=1).rename(name)
    fa = FactorAnalyzer(n_factors=1, rotation=None, method='minres')
    fa.fit(clean)
    loadings = fa.loadings_[:, 0]

    # ── ИСПРАВЛЕНИЕ ЗНАКА ────────────────────────────────────────────────────
    # minres не гарантирует знак первого фактора.
    # Если большинство нагрузок отрицательные — весь фактор перевёрнут.
    # Инвертируем нагрузки и баллы чтобы высокий балл = высокое значение конструкта.
    n_negative = (loadings < 0).sum()
    sign = -1.0 if n_negative > k / 2 else 1.0
    if sign < 0:
        print(f"  [{name}] ⚠ знак инвертирован (большинство нагрузок < 0)")

    ld  = pd.DataFrame(loadings * sign, index=clean.columns, columns=["F1"])
    var = fa.get_factor_variance()[1][0]
    print(f"  [{name}] нагрузки (после коррекции знака):\n{ld.round(3).to_string()}")
    print(f"  [{name}] дисперсия: {var*100:.1f}%")

    raw_scores = fa.transform(clean)[:, 0] * sign
    out = pd.Series(np.nan, index=bat.index, name=name)
    out.update(pd.Series(raw_scores, index=clean.index))
    return out


def run_mca_svd(df, cols, name):
    """MCA через SVD для порядковых/номинальных переменных."""
    avail = [c for c in df.columns if c.upper() in [x.upper() for x in cols]]
    if not avail:
        return None
    sub = df[avail].apply(pd.to_numeric, errors='coerce').dropna().astype(int)
    if len(sub) < 50:
        return None
    dummies = pd.get_dummies(sub.astype(str)).astype(float)
    Z = dummies.values
    P = Z / Z.sum()
    r, c = P.sum(axis=1), P.sum(axis=0)
    S = (P - np.outer(r, c)) / np.outer(np.sqrt(r), np.sqrt(c))
    U, sv, _ = np.linalg.svd(S, full_matrices=False)
    print(f"  [{name}] MCA-SVD n={len(sub)}  sv1={sv[0]:.3f} sv2={sv[1]:.3f}")
    out = pd.Series(np.nan, index=df.index, name=name)
    out.update(pd.Series(U[:, 0], index=sub.index))
    return out


print("✓ Функции анализа готовы")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 5 — Конструкты (базовые)
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*60)
print("КОНСТРУКТЫ")
print("="*60)

scores = {}

# ── 2017 ──────────────────────────────────────────────────────────────────────
if df17 is not None:

    print("\n--- perceived_control [2017] ---")
    # Генерализованный локус контроля: ощущение контроля над жизнью в целом.
    # O29: достигаю целей 1=правда..7=неправда → инверт (высокий = достигаю)
    # O28A: чувствовал несчастье 1=никогда..5=очень часто → инверт (высокий = не несчастен)
    # O28B: не справляюсь 1=никогда..5=очень часто → инверт (высокий = справляюсь)
    # B41: сводить бюджет 1=очень трудно..5=очень легко → без инверт
    # B31: позиция на лестнице 1=вершина..10=низ → инверт
    # O27: здоровье 1=отлично..5=плохо → инверт; код 6 = nevie → маска
    bat = build_battery(df17, {
        'O29':  (True,  [8]),
        'O28A': (True,  [6]),   # v7: исправлен на True (в v6 был False — ошибка)
        'O28B': (True,  [6]),   # v7: исправлен на True
        'B41':  (False, [6]),
        'B31':  (True,  None),
        'O27':  (True,  [6]),
    })
    scores['perceived_control'] = norm01(run_efa(bat, 'perceived_control'))

    print("\n--- social_embeddedness [2017] ---")
    # Включённость в социальную сеть: качество отношений + активность.
    # O36A-F: качество отношений 1-10 (шкала без sentinel 6)
    # O39: активность vs сверстники 1=намного реже..5=намного чаще; код 6 = nevie
    # Примечание: O17 удалён — частота встреч перекрывается с O36 по смыслу
    bat = build_battery(df17, {
        'O36A': (False, None),
        'O36B': (False, None),
        'O36C': (False, None),
        'O36D': (False, None),
        'O36E': (False, None),
        'O36F': (False, None),
        'O39':  (False, [6]),
    })
    scores['social_embeddedness'] = norm01(run_efa(bat, 'social_embeddedness'))

    print("\n--- social_domain_weight [2017] ---")
    # Чувствительность к социальному домену: одиночество + качество слабых связей.
    # O09A-C: одиночество 1=никогда..5=часто; код 6 = nevie
    # O36G: качество связей с коллегами (инверт — низкое качество = высокая чувствит.)
    # O36F: качество связей с соседями (инверт)
    bat = build_battery(df17, {
        'O09A': (False, [6]),
        'O09B': (False, [6]),
        'O09C': (False, [6]),
        'O36G': (True,  None),
        'O36F': (True,  None),
    })
    scores['social_domain_weight'] = norm01(run_efa(bat, 'social_domain_weight'))

    print("\n--- strong_ties_quality [2017] ---")
    # Качество сильных связей: отношения с близкими людьми 1-10.
    # Эталонный конструкт (59–64% дисперсии, KMO=0.875).
    bat = build_battery(df17, {
        'O36A': (False, None),
        'O36B': (False, None),
        'O36C': (False, None),
        'O36D': (False, None),
        'O36E': (False, None),
        'O36F': (False, None),
    })
    scores['strong_ties_quality'] = norm01(run_efa(bat, 'strong_ties_quality'))

    print("\n--- future_orientation [2017] ---")
    # Субъективный оптимизм и ориентация на будущее.
    # O30: удовлетворённость жизнью 1=очень..7=совсем нет; код 8 → инверт
    # O29: достигаю целей 1=правда..7=неправда; код 8 → инверт
    # B31: позиция на лестнице 1=вершина..10=низ → инверт
    # O28A: несчастье 1=никогда..5=часто; код 6 → инверт
    bat = build_battery(df17, {
        'O30':  (True,  [8]),
        'O29':  (True,  [8]),
        'B31':  (True,  None),
        'O28A': (True,  [6]),
    })
    scores['future_orientation'] = norm01(run_efa(bat, 'future_orientation'))

    print("\n--- info_seeking [2017] ---")
    # Интенсивность и каналы поиска информации (офлайн + онлайн).
    # B06: частота интернета 1=ежедневно..6=никогда; код 7 → инверт
    # B08: доля новостей онлайн 1=нет..10=все
    # B09_DIGITAL: бинарный — использует ли интернет/мессенджеры как канал
    # B05: количество источников информации
    b09_s = get_col(df17, 'B09', mask=[5])
    b09_bin = (b09_s == 3).astype(float).where(b09_s.notna(), np.nan)
    df17_b09 = df17.copy()
    df17_b09['B09_DIGITAL'] = b09_bin
    bat = build_battery(df17_b09, {
        'B06':         (True,  [7]),
        'B08':         (False, None),
        'B09_DIGITAL': (False, None),
        'B05':         (False, None),
    })
    scores['info_seeking'] = norm01(run_efa(bat, 'info_seeking'))

    print("\n--- weak_ties_utility [2017] (9 ситуаций) ---")
    # Использование социальной сети (семья/друзья) при решении жизненных задач.
    # O07B-E: к кому обращался за советом (1-3 = сеть, 4-7 = внешние/никто)
    # O08A-E: к кому за практической помощью (1 = сеть, 2+ = внешние/никто)
    # Код 8 = nevie во всех переменных
    wt_df = df17.copy()
    for var, is_network in [
        ('O07B', lambda s: (s >= 1) & (s <= 3)),
        ('O07C', lambda s: (s >= 1) & (s <= 3)),
        ('O07D', lambda s: (s >= 1) & (s <= 3)),
        ('O07E', lambda s: (s >= 1) & (s <= 3)),
        ('O08A', lambda s: s == 1),
        ('O08B', lambda s: s == 1),
        ('O08C', lambda s: s == 1),
        ('O08D', lambda s: s == 1),
        ('O08E', lambda s: s == 1),
    ]:
        raw = get_col(df17, var, mask=[8])
        wt_df[f'{var}_NET'] = is_network(raw).astype(float).where(raw.notna(), np.nan)

    net_cols = [f'{v}_NET' for v in ['O07B','O07C','O07D','O07E','O08A','O08B','O08C','O08D','O08E']
                if f'{v}_NET' in wt_df.columns]
    sub = wt_df[net_cols]
    wt_score = (sub.sum(axis=1) / sub.notna().sum(axis=1).replace(0, np.nan)).rename('weak_ties_utility')
    scores['weak_ties_utility'] = norm01(wt_score)
    print(f"    Доля через сеть (9 ситуаций): mean={wt_score.mean():.3f}  n={wt_score.notna().sum()}")

    print("\n--- network_location [2017] ---")
    # Bernoulli: есть ли хотя бы один удалённый близкий контакт.
    # O21-O25: частота встреч 1=ежедневно..8=никогда
    # 6-8 = редко/никогда = "удалённый"; 9 = нет такого; 10 = живёт вместе → маска
    nl_cols = ['O21','O22','O23','O24','O25']
    nl_df = pd.concat([get_col(df17, v, mask=[9,10]) for v in nl_cols], axis=1)
    has_remote = ((nl_df >= 6) & (nl_df <= 8)).any(axis=1).astype(float)
    has_remote[nl_df.isna().all(axis=1)] = np.nan
    scores['network_location'] = has_remote.rename('network_location')
    print(f"    Удалённые связи: {has_remote.mean():.1%}  n={has_remote.notna().sum()}")


# ── 2022 ──────────────────────────────────────────────────────────────────────
if df22 is not None:

    print("\n--- family_domain_weight [2022] ---")
    # Важность семейного домена: межпоколенческие обязательства и опора на семью.
    # n24: на кого полагаться 0=никто..7=друзья → инверт (низкий = семья)
    # n25: кто важнее 1=родственники..7=друзья → без инверт
    # n22a/b: межпоколенческая помощь 1=обязательно..7=нет → инверт
    # n23: финансовая помощь внуку 1=обязательно..7=нет → инверт
    bat = build_battery(df22, {
        'n24':  (True,  None),
        'n25':  (False, None),
        'n22a': (True,  None),
        'n22b': (True,  None),
        'n23':  (True,  None),
    })
    scores['family_domain_weight'] = norm01(run_efa(bat, 'family_domain_weight'))

    print("\n--- economic_sensitivity [2022] ---")
    # Чувствительность к экономическому домену: финансовые трудности и нагрузка.
    # n28a: сводить концы 1=очень трудно..5=легко → инверт
    # n28b: изменение финансов 1=лучше..5=хуже → без инверт
    # b24: субъективная оценка финансового положения → инверт
    # b32: объективный показатель нагрузки → инверт; код 10 маска
    bat = build_battery(df22, {
        'n28a': (True,  [-8,-9]),
        'n28b': (False, [-8,-9]),
        'b24':  (True,  [-8,-9]),
        'b32':  (True,  [10]),
    })
    scores['economic_sensitivity'] = norm01(run_efa(bat, 'economic_sensitivity'))

    print("\n--- satisfaction_baseline [2022] ---")
    # Базовый уровень удовлетворённости жизнью (одна переменная).
    # R26: счастье 1=очень..7=несчастен → инверт
    s = get_col(df22, 'r26', invert=True)
    scores['satisfaction_baseline'] = norm01(s.rename('satisfaction_baseline'))
    print(f"    r26 (инверт): mean={s.mean():.2f}  n={s.notna().sum()}")

    print("\n--- historical_shock [2022] ---")
    # Hurdle-модель (v8):
    #   Шаг 1: был ли шок? Bernoulli(p_shock)
    #   Шаг 2: если да — насколько сильный? (интенсивность)
    # BSK2: пережил шок (1=да, 2=нет)
    # BSK3: серьёзность (1=нет доп..5=сильный) — только для переживших
    bsk2 = get_col(df22, 'bsk2').map({1:1.0, 2:0.0})
    bsk3 = get_col(df22, 'bsk3')
    # Доля переживших шок (для hurdle: Bernoulli p)
    p_shock = float(bsk2.mean()) if bsk2.notna().sum() > 0 else 0.30
    shock = (bsk2.fillna(0) * bsk3.fillna(0)).rename('historical_shock')
    scores['historical_shock'] = norm01(shock)
    # Сохраняем p_shock для экспорта (используется в agents.py для hurdle)
    scores['historical_shock'].attrs['p_shock'] = round(p_shock, 4)
    print(f"    Пережили шок: {(bsk2==1).sum()} (p_shock={p_shock:.1%})")


# ── 2016 ──────────────────────────────────────────────────────────────────────
if df16 is not None:

    print("\n--- economic_gap [2016] ---")
    # Разрыв между важностью аспектов работы и их реальным состоянием.
    # Q2_1-4: важность 1=очень..5=не важно
    # Q12_1-4: реальность 1=хорошо..5=плохо
    # Gap = (Q2 - Q12): положительный = важно, но плохо = высокий gap
    # Примечание: выборка только занятых (~50% от 2016)
    q2  = pd.concat([get_col(df16, f'Q2_{i}')  for i in range(1,5)], axis=1).mean(axis=1)
    q12 = pd.concat([get_col(df16, f'Q12_{i}') for i in range(1,5)], axis=1).mean(axis=1)
    gap = (q2 - q12).rename('economic_gap')
    scores['economic_gap'] = norm01(gap)
    print(f"    economic_gap: mean={gap.mean():.3f}  n={gap.notna().sum()}")

    print("\n--- job_loss_fear [2016] ---")
    # Страх потерять работу (одна переменная).
    # Q28: 1=очень боюсь..4=не боюсь → инверт (высокий = высокий страх)
    s = get_col(df16, 'Q28', invert=True)
    scores['job_loss_fear'] = norm01(s.rename('job_loss_fear'))
    print(f"    Q28 (инверт): mean={s.mean():.2f}  n={s.notna().sum()}")

    print("\n--- econ_perceived_control [2016] ---")
    # Субъективный контроль в рабочей сфере: удовлетворённость работой
    # и организационная идентификация. Содержательно отличается от
    # perceived_control (2017) — там локус контроля жизни в целом,
    # здесь — позиция в конкретном рабочем контексте.
    # Q12_1: уверенность в сохранении работы → инверт
    # Q28: страх потерять работу (без инверт: высокий страх = низкий контроль)
    # Q23: удовлетворённость работой 1=очень..7=нет → инверт (нагрузка -0.801 в v6)
    # Q22_1: баланс работа-жизнь → инверт
    # Q24_2: гордость фирмой → инверт
    # Q25_2: гордость типом работы → инверт
    bat = build_battery(df16, {
        'Q12_1': (True,  [6]),
        'Q28':   (False, [9]),
        'Q23':   (True,  [99]),
        'Q22_1': (True,  [6]),
        'Q24_2': (True,  [6]),
        'Q25_2': (True,  [6]),
    })
    scores['econ_perceived_control'] = norm01(run_efa(bat, 'econ_perceived_control'))
    # Примечание: job_satisfaction как отдельный конструкт удалён в v7.
    # Q23 входит в econ_perceived_control с нагрузкой ~0.80.
    # Дублирование устранено. Параметр job_satisfaction_init в agents.py
    # заменяется на econ_perceived_control.

    print("\n--- mobility thresholds [2016] ---")
    # Q29_4/5/6/7: готовность к переезду/маятнику/эмиграции.
    # 1=согласен..5=нет; код 6 = nevie → инверт (высокий = высокая готовность)
    for construct, var_list in [
        ('commuter_threshold',     ['Q29_4']),
        ('internal_mig_threshold', ['Q29_5']),
        ('external_mig_threshold', ['Q29_6', 'Q29_7']),
    ]:
        vals = pd.concat([get_col(df16, v, invert=True, mask=[6]) for v in var_list], axis=1).mean(axis=1)
        scores[construct] = norm01(vals.rename(construct))
        print(f"    {construct}: mean={vals.mean():.2f}  n={vals.notna().sum()}")

    print("\n--- job_flexibility [2016] (Q29_1-3) ---")
    # Гибкость в отношении работы: готовность к изменениям условий.
    # Q29_1: новые навыки, Q29_2: снижение зарплаты, Q29_3: временная занятость
    # 1=согласен..5=нет; код 6 = nevie → инверт (высокий = высокая гибкость)
    job_flex_vars = ['Q29_1', 'Q29_2', 'Q29_3']
    vals = pd.concat([get_col(df16, v, invert=True, mask=[6]) for v in job_flex_vars], axis=1).mean(axis=1)
    scores['job_flexibility'] = norm01(vals.rename('job_flexibility'))
    print(f"    job_flexibility: mean={vals.mean():.2f}  n={vals.notna().sum()}")

    print("\n--- work_family_conflict [2016] ---")
    # Конфликт между работой и семейной жизнью.
    # Q19_1/2: прямые вопросы о конфликте 1=всегда..5=никогда; без инверт
    # Q14_2: работа по выходным; без инверт (часто = высокий конфликт)
    # Q18: трудно отключиться от работы → инверт; код 99 маска
    # Q22_1/2: неудовлетворённость балансом → инверт; код 6 маска
    bat = build_battery(df16, {
        'Q19_1': (False, [6]),
        'Q19_2': (False, [6]),
        'Q14_2': (False, [6]),
        'Q18':   (True,  [99]),
        'Q22_1': (True,  [6]),
        'Q22_2': (True,  [6]),
    })
    scores['work_family_conflict'] = norm01(run_efa(bat, 'work_family_conflict'))

    print("\n--- org_loyalty [2016] ---")
    # Организационная лояльность и привязанность к текущему месту работы.
    # Q24_1-3: готов работать сверх / горжусь фирмой / откажу от предложения 1=да..5=нет
    # Q25_1: хочу сменить работу → инверт
    # Q25_2: горжусь типом работы
    # код 6 = nevie во всех переменных
    bat = build_battery(df16, {
        'Q24_1': (False, [6]),
        'Q24_2': (False, [6]),
        'Q24_3': (False, [6]),
        'Q25_1': (True,  [6]),
        'Q25_2': (False, [6]),
    })
    scores['org_loyalty'] = norm01(run_efa(bat, 'org_loyalty'))

    print("\n--- place_aspiration [2016] ---")
    # Амбиции и ориентация на достижения (связь с местом через образование/карьеру).
    # OQ1_3/4/12/14/15: важность образования/амбиций/региона/смелости/языков
    # 1=очень важно..5=не важно; код 6 = nevie
    avail = [v for v in ['OQ1_3','OQ1_4','OQ1_12','OQ1_14','OQ1_15'] if v in df16.columns]
    if len(avail) >= 3:
        bat = build_battery(df16, {v: (False, [6]) for v in avail})
        scores['place_aspiration'] = norm01(run_efa(bat, 'place_aspiration'))
    else:
        vals = pd.concat([get_col(df16, v, mask=[6]) for v in avail], axis=1).mean(axis=1)
        scores['place_aspiration'] = norm01(vals.rename('place_aspiration'))
        print(f"    Fallback на среднее ({avail})")

    print("\n--- network_job_search [2016] ---")
    # Bernoulli: использовал ли агент сеть при поиске работы.
    # Q40_6: 1=нет, 2=да 1-2 раза, 3=да 3+ раза → >=2 = использовал
    # Q35A: как нашёл работу — код 6/7 = через семью/знакомых
    q40 = get_col(df16, 'Q40_6')
    s40 = (q40 >= 2).astype(float).where(q40.notna(), np.nan)
    print(f"    Q40_6 ≥ 2: {s40.mean():.1%}  n={s40.notna().sum()}")
    q35a = get_col(df16, 'Q35A', mask=[9])
    s35a = ((q35a == 6) | (q35a == 7)).astype(float).where(q35a.notna(), np.nan)
    print(f"    Q35A коды 6/7 (семья/знакомые): {s35a.mean():.1%}  n={s35a.notna().sum()}")
    combined = pd.concat([s40, s35a], axis=1).mean(axis=1)
    scores['network_job_search'] = combined.rename('network_job_search')
    print(f"    Объединённый p: {combined.mean():.1%}")


# ── 2024 ──────────────────────────────────────────────────────────────────────
if df24 is not None:

    print("\n--- digital_comm_intensity [2024] ---")
    # Q11_A: частота онлайн-коммуникации 1=очень часто..5=никогда → инверт
    s = get_col(df24, 'Q11_A', invert=True)
    scores['digital_comm_intensity'] = norm01(s.rename('digital_comm_intensity'))
    print(f"    Q11_A (инверт): mean={s.mean():.2f}  n={s.notna().sum()}")

    print("\n--- info_quality_digital [2024] ---")
    # Самооценка цифровых навыков: поиск, оценка, работа с информацией.
    # Q10_A-D: 1=отлично..5=плохо → инверт в батарее
    # Коррекция знака EFA применяется автоматически через run_efa v7.
    bat = build_battery(df24, {k: (True, None) for k in ['Q10_A','Q10_B','Q10_C','Q10_D']})
    scores['info_quality_digital'] = norm01(run_efa(bat, 'info_quality_digital'))

    print("\n--- network_signal_susceptibility [2024] (среднее Q13_A-C, инверт) ---")
    # Критическое потребление информации: проверка источников.
    # Q13_A-C: 1=часто..5=никогда → инверт (высокий = часто проверяет)
    q13a = get_col(df24, 'Q13_a', invert=True)
    q13b = get_col(df24, 'Q13_b', invert=True)
    q13c = get_col(df24, 'Q13_c', invert=True)
    nss = (q13a + q13b + q13c) / 3
    scores['network_signal_susceptibility'] = norm01(nss.rename('network_signal_susceptibility'))
    print(f"    mean={nss.mean():.3f}  n={nss.notna().sum()}")

    print("\n--- digital_trust [2024] ---")
    # Q_14: доверие к онлайн-незнакомцам 0-10
    s = get_col(df24, 'Q_14')
    scores['digital_trust'] = norm01(s.rename('digital_trust'))
    print(f"    Q_14 (0-10): mean={s.mean():.2f}  n={s.notna().sum()}")


print(f"\n✓ Конструктов (базовых): {len(scores)}")
for k, s in scores.items():
    print(f"  {k:42s} n={s.count():4d}  mean={s.mean():.3f}  std={s.std():.3f}")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 5b — Составные параметры (новое в v7)
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*60)
print("СОСТАВНЫЕ ПАРАМЕТРЫ (v7)")
print("="*60)

def composite_from_variance(component_names, scores_dict, efa_variance, out_name):
    """
    Строит составной параметр как взвешенное среднее групповых средних.
    Веса = нормированная объяснённая дисперсия EFA каждого компонента.

    Поскольку компоненты из разных опросов (разные индексы), агрегация
    выполняется через групповые средние по (age_group, edu_group),
    а не через слияние индивидуальных наблюдений.

    Возвращает словарь {(age_group, edu_group): weighted_mean}
    для использования в group_stats на уровне агрегатов.
    """
    available = [(n, efa_variance[n]) for n in component_names
                 if n in scores_dict and n in efa_variance]
    if not available:
        print(f"  [{out_name}] ✗ компоненты не найдены")
        return None

    total_var = sum(v for _, v in available)
    weights   = {n: v / total_var for n, v in available}
    print(f"  [{out_name}] компоненты и веса (из дисперсии EFA):")
    for n, w in weights.items():
        print(f"    {n}: {efa_variance[n]:.1f}% → вес {w:.3f}")
    return weights


print("\n--- info_quality_final ---")
# Реальная способность агента получать и обрабатывать информацию о районах.
# info_seeking (2017): интенсивность + каналы поиска
# info_quality_digital (2024): качество цифровых навыков
# Веса экспертные: 0.35 / 0.65 (навыки важнее частоты)
IQ_WEIGHTS = COMPOSITE_WEIGHTS['info_quality_final']
print(f"  [info_quality_final] экспертные веса: {IQ_WEIGHTS}")
scores['info_quality_final'] = None   # заполняется через групповые агрегаты в ячейке 6b

print("\n--- inertia_social_component ---")
# Социальная составляющая инерции: качество и глубина социальных связей.
# social_embeddedness (2017): включённость в сеть
# strong_ties_quality (2017): качество сильных связей
# family_domain_weight (2022): семейные обязательства
# Веса экспертные: 0.30 / 0.40 / 0.30 (сильные связи — главный якорь)
ISC_WEIGHTS = COMPOSITE_WEIGHTS['inertia_social_component']
print(f"  [inertia_social_component] экспертные веса: {ISC_WEIGHTS}")
scores['inertia_social_component'] = None  # заполняется через групповые агрегаты в ячейке 6b

print("\n✓ Веса составных параметров определены")
print("  Финальные значения будут вычислены в Ячейке 6b через групповые агрегаты.")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 6 — Регрессия по демографическим группам (базовые конструкты)
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*60)
print("РЕГРЕССИЯ ПО ГРУППАМ")
print("="*60)

SOURCES = {
    'perceived_control':             (demo17, ['age_group','edu_group']),
    'social_embeddedness':           (demo17, ['age_group','edu_group','settlement']),
    'social_domain_weight':          (demo17, ['age_group','edu_group']),
    'strong_ties_quality':           (demo17, ['age_group','edu_group']),
    'future_orientation':            (demo17, ['age_group','edu_group','settlement']),
    'info_seeking':                  (demo17, ['age_group','edu_group']),
    'weak_ties_utility':             (demo17, ['age_group','edu_group']),
    'network_location':              (demo17, ['age_group','edu_group']),
    'family_domain_weight':          (demo22, ['age_group','edu_group']),
    'economic_sensitivity':          (demo22, ['age_group','edu_group']),
    'satisfaction_baseline':         (demo22, ['age_group','edu_group']),
    'historical_shock':              (demo22, ['age_group','edu_group']),
    'economic_gap':                  (demo16, ['age_group','edu_group']),
    'job_loss_fear':                 (demo16, ['age_group','edu_group']),
    'econ_perceived_control':        (demo16, ['age_group','edu_group']),
    # job_satisfaction удалён в v7 — Q23 входит в econ_perceived_control
    # ═══ v8: settlement для ключевых миграционных параметров ═══
    'commuter_threshold':            (demo16, ['age_group','edu_group','settlement']),
    'internal_mig_threshold':        (demo16, ['age_group','edu_group','settlement']),
    'external_mig_threshold':        (demo16, ['age_group','edu_group','settlement']),
    'job_flexibility':               (demo16, ['age_group','edu_group','settlement']),
    'work_family_conflict':          (demo16, ['age_group','edu_group']),
    'org_loyalty':                   (demo16, ['age_group','edu_group']),
    'place_aspiration':              (demo16, ['age_group','edu_group']),
    'network_job_search':            (demo16, ['age_group','edu_group']),
    'digital_comm_intensity':        (demo24, ['age_group','edu_group']),
    'info_quality_digital':          (demo24, ['age_group','edu_group']),
    'network_signal_susceptibility': (demo24, ['age_group','edu_group']),
    'digital_trust':                 (demo24, ['age_group','edu_group']),
}


def group_stats(score, demo, gcols, name):
    valid  = [c for c in gcols if demo is not None and c in demo.columns]
    if not valid:
        return {}, float(score.mean()), float(score.std())
    merged = pd.concat([score.rename('s'), demo[valid]], axis=1).dropna()
    gm, gs = float(merged['s'].mean()), float(merged['s'].std())
    print(f"  [{name}] global mean={gm:.3f} std={gs:.3f} n={len(merged)}")
    by_group = {}
    for gvals, sub in merged.groupby(valid, observed=True):
        if len(sub) < 8:
            continue
        key = str(gvals) if isinstance(gvals, tuple) else str((gvals,))
        by_group[key] = {
            "mean": round(float(sub['s'].mean()), 4),
            "std":  round(float(sub['s'].std()),  4),
            "p25":  round(float(sub['s'].quantile(.25)), 4),
            "p75":  round(float(sub['s'].quantile(.75)), 4),
            "n":    int(len(sub)),
        }
    return by_group, gm, gs


model_params = {}
for construct, (demo, gcols) in SOURCES.items():
    if construct not in scores or scores[construct] is None or demo is None:
        continue
    by_group, gm, gs = group_stats(scores[construct], demo, gcols, construct)
    model_params[construct] = {"global_mean": round(gm,4),
                                "global_std":  round(gs,4),
                                "by_group":    by_group}

print(f"\n✓ Параметров (базовых): {len(model_params)}")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 6b — Составные параметры: агрегация через групповые средние
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*60)
print("СОСТАВНЫЕ ПАРАМЕТРЫ: ГРУППОВЫЕ АГРЕГАТЫ")
print("="*60)

def build_composite_group_stats(component_weights, model_params, out_name):
    """
    Вычисляет составной параметр через взвешенное среднее групповых средних.

    Для каждой демографической группы (age_group, edu_group):
      composite_mean = sum(weight_i * component_mean_i) / sum(weight_i_available)

    Стандартное отклонение вычисляется как взвешенное среднее SD компонент
    (консервативная оценка — без учёта ковариации между опросами).

    Группы включаются только если присутствуют хотя бы в 2 компонентах.
    """
    # Собираем все ключи групп из всех компонент
    all_keys = set()
    for name in component_weights:
        if name in model_params:
            all_keys.update(model_params[name]['by_group'].keys())

    by_group = {}
    weight_vals = list(component_weights.values())
    comp_names  = list(component_weights.keys())

    for key in sorted(all_keys):
        comp_data = [(component_weights[n], model_params[n]['by_group'][key])
                     for n in comp_names
                     if n in model_params and key in model_params[n]['by_group']]
        if len(comp_data) < 2:
            continue
        total_w = sum(w for w, _ in comp_data)
        w_mean  = sum(w * d['mean'] for w, d in comp_data) / total_w
        w_std   = sum(w * d['std']  for w, d in comp_data) / total_w
        min_n   = min(d['n'] for _, d in comp_data)
        by_group[key] = {
            "mean": round(w_mean, 4),
            "std":  round(w_std,  4),
            "p25":  round(w_mean - 0.674 * w_std, 4),  # приближение нормального
            "p75":  round(w_mean + 0.674 * w_std, 4),
            "n":    min_n,
            "n_components": len(comp_data),
        }

    if not by_group:
        print(f"  [{out_name}] ✗ нет групп с достаточным перекрытием")
        return None

    gm = sum(v['mean'] for v in by_group.values()) / len(by_group)
    gs = sum(v['std']  for v in by_group.values()) / len(by_group)
    print(f"  [{out_name}] global mean={gm:.3f}  std={gs:.3f}  groups={len(by_group)}")

    return {"global_mean": round(gm, 4),
            "global_std":  round(gs, 4),
            "by_group":    by_group,
            "composite_weights": {k: round(v, 4) for k, v in component_weights.items()}}


if IQ_WEIGHTS:
    res = build_composite_group_stats(IQ_WEIGHTS, model_params, 'info_quality_final')
    if res:
        model_params['info_quality_final'] = res

if ISC_WEIGHTS:
    res = build_composite_group_stats(ISC_WEIGHTS, model_params, 'inertia_social_component')
    if res:
        model_params['inertia_social_component'] = res

print(f"\n✓ Итого параметров (с составными): {len(model_params)}")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 7 — Региональные профили
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*60)
print("РЕГИОНАЛЬНЫЕ ПРОФИЛИ")
print("="*60)

# Составные параметры не имеют прямого регионального профиля
# (компоненты из разных опросов с разной региональной выборкой).
# Их региональный профиль вычисляется в ЯЧЕЙКЕ 7b через взвешивание.

MAPPING = {
    # ── Психологические ──────────────────────────────────────────────────────
    "perceived_control":             ("perceived_control",              1.0,  0.0),
    "econ_perceived_control":        ("econ_perceived_control",         1.0,  0.0),
    # ── Социальная сеть ──────────────────────────────────────────────────────
    "social_domain_weight":          ("domain_social_weight",           0.35, 0.0),
    "weak_ties_utility":             ("weak_ties_utility",              1.0,  0.0),
    "network_location":              ("network_location",               1.0,  0.0),
    "network_job_search":            ("network_job_search",             1.0,  0.0),
    # ── Семья ────────────────────────────────────────────────────────────────
    "work_family_conflict":          ("family_weight_modifier",         0.15, 0.0),
    # ── Экономика ────────────────────────────────────────────────────────────
    "economic_sensitivity":          ("domain_economic_weight",         0.55, 0.0),
    "economic_gap":                  ("domain_economic_gap",            1.0,  0.0),
    "job_loss_fear":                 ("domain_economic_threshold",     -0.6,  0.8),
    # ── Будущее ──────────────────────────────────────────────────────────────
    "future_orientation":            ("domain_future_value",            1.0,  0.0),
    "place_aspiration":              ("domain_future_place",            1.0,  0.0),
    # ── Мобильность ──────────────────────────────────────────────────────────
    "commuter_threshold":            ("commuter_mode_threshold",        1.0,  0.0),
    "internal_mig_threshold":        ("internal_mig_threshold",         1.0,  0.0),
    "external_mig_threshold":        ("external_mig_threshold",         1.0,  0.0),
    "job_flexibility":               ("job_flexibility_threshold",      1.0,  0.0),
    # ── Инерция ──────────────────────────────────────────────────────────────
    "org_loyalty":                   ("tenure_loyalty_bonus",           0.15, 0.0),
    "historical_shock":              ("inertia_shock_sensitivity",      0.2,  0.0),
    # ── Инициализация ────────────────────────────────────────────────────────
    "satisfaction_baseline":         ("satisfaction_init",              1.0,  0.0),
    # ── Цифровые ─────────────────────────────────────────────────────────────
    "digital_comm_intensity":        ("digital_comm_intensity",         1.0,  0.0),
    "network_signal_susceptibility": ("network_signal_susceptibility",  1.0,  0.0),
    "digital_trust":                 ("digital_trust",                  1.0,  0.0),
    # ── Составные (v7) ───────────────────────────────────────────────────────
    "info_quality_final":            ("info_quality_modifier",          1.0,  0.0),
    "inertia_social_component":      ("inertia_social_component",       1.0,  0.0),
}

BERNOULLI_PARAMS = {'network_job_search', 'network_location'}

def sc(v, scale, offset):
    return round(float(offset + v * scale), 4)

regional_raw    = {}
regional_mapped = {}

# Региональные профили для базовых конструктов из индивидуальных данных
for construct, (demo, _) in SOURCES.items():
    if construct not in scores or scores[construct] is None:
        continue
    if demo is None or 'region' not in demo.columns:
        continue
    merged = pd.concat([scores[construct].rename('s'), demo['region']], axis=1).dropna()
    if len(merged) < 20:
        continue
    reg = {}
    for r, sub in merged.groupby('region'):
        if len(sub) < 5:
            continue
        reg[str(r)] = {"mean": round(float(sub['s'].mean()), 4),
                       "std":  round(float(sub['s'].std()),  4),
                       "n":    int(len(sub))}
    if reg:
        regional_raw[construct] = reg
        top = sorted(reg.items(), key=lambda x: x[1]['mean'], reverse=True)
        print(f"  {construct}: " + " | ".join(f"{r}={v['mean']:.3f}(n={v['n']})" for r,v in top[:4]))

for construct, (param, scale, offset) in MAPPING.items():
    if construct not in regional_raw:
        continue
    regional_mapped[param] = {
        r: {"mean": sc(v["mean"], scale, offset),
            "std":  round(float(v["std"] * abs(scale)), 4),
            "n":    v["n"]}
        for r, v in regional_raw[construct].items()
    }

print(f"\n✓ Региональные профили (базовые): {len(regional_mapped)} параметров")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 7b — Региональные профили для составных параметров
# ══════════════════════════════════════════════════════════════════════════════
print("\n--- Региональные профили составных параметров ---")

def composite_regional(component_weights, regional_raw, param_name, scale=1.0, offset=0.0):
    """
    Региональный профиль составного параметра через взвешенное среднее
    региональных профилей компонент. Регион включается только если
    присутствует хотя бы в 2 компонентах.
    """
    comp_names = list(component_weights.keys())
    all_regions = set()
    for n in comp_names:
        if n in regional_raw:
            all_regions.update(regional_raw[n].keys())

    result = {}
    for r in sorted(all_regions):
        comp_data = [(component_weights[n], regional_raw[n][r])
                     for n in comp_names
                     if n in regional_raw and r in regional_raw[n]]
        if len(comp_data) < 2:
            continue
        total_w = sum(w for w, _ in comp_data)
        w_mean  = sum(w * d['mean'] for w, d in comp_data) / total_w
        w_std   = sum(w * d['std']  for w, d in comp_data) / total_w
        min_n   = min(d['n'] for _, d in comp_data)
        result[r] = {"mean": sc(w_mean, scale, offset),
                     "std":  round(w_std * abs(scale), 4),
                     "n":    min_n}
    if result:
        top = sorted(result.items(), key=lambda x: x[1]['mean'], reverse=True)
        print(f"  {param_name}: " + " | ".join(f"{r}={v['mean']:.3f}(n={v['n']})" for r,v in top[:4]))
    return result

if IQ_WEIGHTS:
    regional_mapped['info_quality_modifier'] = composite_regional(
        IQ_WEIGHTS, regional_raw, 'info_quality_modifier')

if ISC_WEIGHTS:
    regional_mapped['inertia_social_component'] = composite_regional(
        ISC_WEIGHTS, regional_raw, 'inertia_social_component')

print(f"\n✓ Региональные профили итого: {len(regional_mapped)} параметров")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 8 — Маппинг + экспорт
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "="*60)
print("МАППИНГ + ЭКСПОРТ")
print("="*60)

agent_params = {}
for construct, (param, scale, offset) in MAPPING.items():
    if construct not in model_params:
        continue
    src   = model_params[construct]
    entry = {
        "global_mean":      sc(src["global_mean"], scale, offset),
        "global_std":       round(float(src["global_std"] * abs(scale)), 4),
        "source_construct": construct,
        "by_group": {
            k: {"mean": sc(v["mean"], scale, offset),
                "std":  round(float(v["std"] * abs(scale)), 4),
                "p25":  sc(v["p25"], scale, offset),
                "p75":  sc(v["p75"], scale, offset),
                "n":    v["n"]}
            for k, v in src["by_group"].items()
        },
    }
    if param in BERNOULLI_PARAMS:
        entry["sampling"] = "bernoulli"
    if "composite_weights" in src:
        entry["composite_weights"] = src["composite_weights"]
    # ═══ v8: p_shock для hurdle-модели shock_sensitivity ═══
    if param == "inertia_shock_sensitivity" and construct in scores and scores[construct] is not None:
        p_shock_val = getattr(scores[construct], 'attrs', {}).get('p_shock', 0.30)
        entry["p_shock"] = round(float(p_shock_val), 4)
    agent_params[param] = entry
    print(f"  {param:44s} mean={entry['global_mean']:.3f}  groups={len(entry['by_group'])}"
          + ("  [bernoulli]" if param in BERNOULLI_PARAMS else "")
          + ("  [composite]" if "composite_weights" in src else ""))

agent_params['_regional'] = regional_mapped

def serial(o):
    if isinstance(o, np.integer):  return int(o)
    if isinstance(o, np.floating): return float(o)
    if isinstance(o, np.ndarray):  return o.tolist()
    raise TypeError(type(o))

with open(OUT_JSON, "w", encoding="utf-8") as f:
    json.dump(agent_params, f, ensure_ascii=False, indent=2, default=serial)
print(f"\n✓ JSON: {OUT_JSON}")

rows = [{"parameter": k,
         "global_mean": v["global_mean"],
         "global_std":  v["global_std"],
         "n_groups":    len(v.get("by_group", {})),
         "sampling":    v.get("sampling", "normal"),
         "composite":   "yes" if "composite_weights" in v else "no",
         "source":      v.get("source_construct", "")}
        for k, v in agent_params.items() if not k.startswith("_")]
summary = pd.DataFrame(rows).sort_values("parameter")
summary.to_csv(OUT_CSV, index=False)
print(f"✓ CSV: {OUT_CSV}")
print(f"\n{summary.to_string(index=False)}")


# ══════════════════════════════════════════════════════════════════════════════
# ЯЧЕЙКА 9 — Интеграция в agents.py
# ══════════════════════════════════════════════════════════════════════════════
print("""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
В agents.py:

import json, numpy as np
with open("agent_params_from_survey.json") as f:
    SURVEY = json.load(f)
REGIONAL = SURVEY.get("_regional", {})
BERNOULLI_PARAMS = {'network_job_search', 'network_location'}

def sample_param(name, age, education, region=None):
    p = SURVEY.get(name)
    if not p: return 0.5
    ag = ("18-30" if age<31 else "31-45" if age<46 else "46-60" if age<61 else "60+")
    eg = ("low"    if education in ["Without education","Basic"]
          else "medium" if "Secondary" in education else "high")
    g  = p["by_group"].get(str((ag, eg)))
    mu = g["mean"] if g else p["global_mean"]
    sd = g["std"]  if g else p["global_std"]
    n  = g["n"]    if g else 1
    if region and name in REGIONAL:
        r = REGIONAL[name].get(region)
        if r and r["n"] > 5:
            w_g = 1 / max(sd / n**0.5, 1e-6)
            w_r = 1 / max(r["std"] / r["n"]**0.5, 1e-6)
            mu  = (w_g * mu + w_r * r["mean"]) / (w_g + w_r)
    if name in BERNOULLI_PARAMS:
        return float(np.random.random() < mu)
    return float(np.clip(np.random.normal(mu, sd), 0., 1.))

# Параметры агента при инициализации (v7):
#   perceived_control           ← локус контроля жизни в целом (2017)
#   econ_perceived_control      ← контроль в рабочей сфере (2016)
#   inertia_social_component    ← составной: social_emb + strong_ties + family (2017+2022)
#   info_quality_modifier       ← составной: info_seeking + info_quality_digital (2017+2024)
#   [job_satisfaction_init удалён — Q23 входит в econ_perceived_control]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")